[features]
seeds = false
[programs.localnet]
mint_exchange = "CGEYAjkfYU696uy1i3XSpn5TzVvprPMTdAbsng9b2jrE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kstepanovdev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
